name: Update Congress Control JSON

on:
  schedule:
    - cron: "15 10 * * *" # daily 10:15 UTC (change if you want)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run updater
        run: node scripts/update_congress_control.js

      - name: Commit & push if changed
        run: |
          git config user.name "unoppress-bot"
          git config user.email "unoppress-bot@users.noreply.github.com"
          git add congress-control.json
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "auto: update congress-control.json"
            git push
          fi

